### ISSUE TITLE
URLs ending with slash causes 404

### ISSUE THREAD

**Issue by FatemeKhodayari** [aulasneo/openedx-rest-api-client#1]
Hi. I'm running openedx olive with tutor. Just found your package as I needed to call the enrollment API. I had no problem with getting courses list but when trying to enroll a user in a course using the `change_enrollment` method, the server responded with 404 as it couldn't find the `https://myopenedx/api/bulk_enroll/v1/bulk_enroll/` endpoint. As I removed the ending slash from `URL_BULKENROLL = '/api/bulk_enroll/v1/bulk_enroll/'`,  everything worked fine. There's also no trailing slash in openedx swagger.

**Comment by angonz** [comment]
Hi @FatemeKhodayari! Thanks for noting this. Please download version 0.0.3 and let me know if it fixed the problem.

**Comment by FatemeKhodayari** [comment]
Thanks a lot @angonz :) It's fixed and works fine.
